### ISSUE TITLE
using unix tools to remove extra stuff from GPG private key

### ISSUE THREAD

**Issue by cameri** [RandyMcMillan/nostr-gpg-keys#1]
`gpg --export-secret-key your-key | grep -v "^-" | tr -d "\n"`

`grep -v '^-'` removes any line starting with `-`
`tr -d "\n"` removes new lines

editing the file with some editor can cause new lines to be added at the end
the new lines are not part of the actual key

**Comment by cameri** [comment]
missed `-v` flag on grep....

**Comment by RandyMcMillan** [comment]
thanks - i know there are better ways to do this - i just havent had time to expand on this. :)

I will add this - but ultimately I plan to stream the key - so it will never be written to file at all! :)
